#!/bin/sh
#
# Run this shell script to bootstrap as necessary after a fresh checkout.

set -e

autoreconf -i --force
rm -rf autom4te.cache

# Generate manual pages.
version=`grep '^kstart' NEWS | head -1 | cut -d' ' -f2`
pod2man --release="$version" --center="kstart" k4start.pod > k4start.1
pod2man --release="$version" --center="kstart" k5start.pod > k5start.1
pod2man --release="$version" --center="kstart" krenew.pod > krenew.1
