=head1 NAME

k5start - Obtain and optionally keep active a Kerberos v5 ticket.

=head1 SYNOPSIS

B<k5start> [B<-nqstv>]
[B<-f> I<keytab>]
[B<-H> I<minutes>]
[B<-I> I<service instance>]
[B<-i> I<client instance>]
[B<-K> I<minutes>]
[B<-k> I<ticket file>]
[B<-l> I<time string>]
[B<-r> I<service realm>]
[B<-S> I<service name>]
[B<-u> I<client principal>]
[I<username> [I<command> ...]]

=head1 DESCRIPTION

B<k5start> obtains and caches an initial Kerberos v5 ticket-granting
ticket for a principal.  B<k5start> can be used as an alternative to
kinit, but it is primarily intended to be used by programs that want to
use a keytab to obtain Kerberos credentials, such as a web server that
needs to authenticate to another service such as an LDAP server.

Normally, the principal for which to give tickets should be specified as
the first argument.  I<username> may be either just a principal name
(including the optional instance) or a full principal and realm string.
The B<-u> and B<-i> options can be used as an alternative mechanism for
specifying the principal, but generally aren't as convenient.  If no
username is given as either the first argument or the argument to the
B<-u> option, the client principal defaults to the Unix username of the
user running B<k5start> in the default local realm.

Optionally, a command may be given on the command line of B<k5start>.  If
so, that command is run after Kerberos authentication (and running
B<aklog> if desired), with the appropriate environment variables set to
point it to the right ticket cache.  B<k5start> will then continue
running, waking up periodically to refresh credentials slightly before
they would expire, until the command completes.  (The frequency with which
it wakes up to refresh credentials can still be controlled with the B<-K>
option.)  To run in this mode, the principal must be specified as a
regular command-line argument rather than using the B<-u> and B<-i>
options and a keytab must be specified with B<-f>.

The command will not be run using the shell, so if you want to use shell
metacharacters in the command with their special meaning, give C<sh -c
I<command>> as the command to run and quote I<command>.

=head1 OPTIONS

=over 4

=item B<-f> I<keytab>
	
Authenticate using the keytab I<keytab> rather than asking for a
password.  A key for the client principal must be present in I<keytab>.

=item B<-H> I<minutes>

Check for a happy ticket, one that has a remaining lifetime of at least
I<minutes> minutes.  If such a ticket is found, exit immediately with
status 0.  Otherwise, try to obtain a new ticket.

=item B<-I> I<service instance>

The instance portion of the service principal.  The default is the default
realm of the machine.  Note that unlike the client principal, a
non-default service principal must be specified with B<-I> and B<-S>; one
cannot provide the instance portion as part of the argument to B<-S>.

=item B<-i> I<client instance>

Specifies the instance portion of the principal.  This option doesn't make
sense except in combination with B<-u>.  Note that the instance can be
specified as part of I<username> through the normal convention of
appending a slash and then the instance, so one never has to use this
option.

=item B<-K> I<minutes>
	
Run in daemon mode to keep a ticket alive indefinitely.  The program
reawakens after I<minutes> minutes, checks if the ticket will expire
before the next wakeup, and gets a new ticket if needed.

=item B<-k> I<ticket file>

Use I<ticket file> as the ticket cache rather than the contents of the
environment variable KRB5CCNAME or the library default.

=item B<-l> I<time string>

Set the ticket lifetime.  I<time string> should be in a format recognized
by the Kerberos libraries for specifying times, such as C<10h> (ten hours)
or C<10m> (ten minutes).  Known units are C<s>, C<m>, C<h>, and C<d>.  For
more information, see kinit(1).

=item B<-n>
	
Ignored, present for option compatibility with B<k4start>.

=item B<-q>
	
Quiet.  Suppresses the printing of the initial banner message saying what
Kerberos principal tickets are being obtained for, and also suppresses the
password prompt when the B<-s> option is given.

=item B<-r> I<service realm>

The realm for the service principal.  This defaults to the default local
realm.

=item B<-S> I<service name>

Specifies the principal for which B<k5start> is getting a service ticket.
The default value is C<krbtgt>, to obtain a ticket-granting ticket.  This
option (along with B<-I>) may be used if one only needs access to a single
service.  Note that unlike the client principal, a non-default service
principal must be specified with both B<-S> and B<-I>; one cannot provide
the instance portion as part of the argument to B<-S>.

=item B<-s>
	
Read the password from standard input.  This bypasses the normal password
prompt, which means echo isn't suppressed and input isn't forced to be
from the controlling terminal.  Most uses of this option are a security
risk.  You normally want to use a keytab and the B<-f> option intead.

=item B<-t>
	
Run an external program after getting a ticket.  The default use of this
is to run B<aklog> to get a token.  If the environment variable KINIT_PROG
is set, it overrides the compiled-in default.

=item B<-u> I<client principal>

This specifies the principal to obtain credentials as.  The entire
principal may be specified here, or alternatively just the first portion
may be specified with this flag and the instance specified with B<-i>.

Note that there's normally no reason to use this flag rather than simply
giving the principal on the command line as the first regular argument.

=item B<-v>
	
Be verbose.  This will print out a bit of additional information about
what is being attempted and what the results are.

=back

=head1 RETURN VALUES

The program exits with status 0 if it successfully gets a ticket or has a
happy ticket (see B<-H>).  If B<k5start> runs aklog or some other program
B<k5start> returns the exit status of that program.

=head1 EXAMPLE

Use the F</etc/krb5.keytab> keytab to obtain a ticket granting ticket for
the principal host/example.com, putting the ticket cache in
F</tmp/service.tkt>.  The lifetime is 10 hours and the program wakes up
every 10 minutes to check if the ticket is about to expire.

    k5start -k /tmp/service.tkt -f /etc/krb5.keytab -K 10 -l 10h \
        host/example.com

Do the same, but using the default ticket cache and run the command
/usr/local/bin/auth-backup.  B<k4start> will continue running until the
command finishes.

    k5start -f /etc/krb5.keytab -K 10 -l 10h host/example.com \
        /usr/local/bin/auth-backup

=head1 ENVIRONMENT

If the environment variable KINIT_PROG is set to a program (such as
B<aklog>) then this path will be used for the program to run with B<-t>
rather than the default compiled into B<k5start>.

If no ticket file is specified on the command line, B<k5start> will use
the environment variable KRB5CCNAME to determine the location of the the
ticket granting ticket.  If the B<-k> option is used, KRB5CCNAME will be
set to point to that file before running the B<aklog> program or any
command given on the command line.

=head1 FILES

The default ticket cache is determined by the underlying Kerberos
libraries.  The default path for aklog is determined at build time, and
will normally be whichever of B<aklog> or B<afslog> is found in the user's
path.

=head1 SEE ALSO

k4start(1), kinit(1)

The kstart web page at L<http://www.eyrie.org/~eagle/software/kstart/>
will have the current version of B<k4start> and B<k5start>.

=head1 AUTHORS

B<k5start> was based on the k4start code written by Robert Morgan.  It was
ported to Kerberos v5 by Booker C. Bense.  Additional cleanup and current
maintenance are done by Russ Allbery <rra@stanford.edu>.

=cut
