#!/usr/bin/perl
#
# Test formatting of POD documentation.
#
# Written by Russ Allbery <rra@stanford.edu>
# Copyright 2008, 2009 Board of Trustees, Leland Stanford Jr. University
#
# See LICENSE for licensing terms.

use Test::More;

my @files = qw(k4start.pod k5start.pod krenew.pod);
my $total = scalar (@files);
plan tests => $total;

eval 'use Test::Pod 1.00';
SKIP: {
    skip 'Test::Pod 1.00 required for testing POD', $total if $@;
    for my $file (@files) {
        pod_file_ok ("$ENV{SOURCE}/../$file", $file);
    }
}
