#!/usr/bin/perl -w
#
# Test formatting of POD documentation.
#
# Written by Russ Allbery <rra@stanford.edu>
# Copyright 2008, 2009, 2011
#     The Board of Trustees of the Leland Stanford Junior University
#
# See LICENSE for licensing terms.

use strict;
use Test::More;

my @podfiles = qw(k5start.pod krenew.pod);

eval 'use Test::Pod 1.00';
plan skip_all => "Test::Pod 1.00 required for testing POD" if $@;
my $srcdir = "$ENV{SOURCE}";
$srcdir =~ s,[^/]+/*$,,;
chdir "$srcdir" or die "$0: cannot chdir to $srcdir: $!\n";
all_pod_files_ok (@podfiles);
